Added support for genepool API
eryph-org/eryph pull request #116
Opened 2024-01-23 23:23 UTC by fw2568

2024-02-08 15:10 UTC, ChristopherMann requested changes

2024-02-08 15:10 UTC, ChristopherMann commented on src/core/test/Eryph.VmManagement.Test/Eryph.VmManagement.Test.csproj
> +    <LangVersion>latest</LangVersion>
Do we need to set the language version? If we need to, we should pin it to a specific version. `default` and `latest` can change depending on the locally installed SDK.

2024-02-08 15:10 UTC, ChristopherMann commented on src/core/src/Eryph.VmManagement/VirtualMachine.cs
> +                var parentIdentifier = GeneSetIdentifier.ParseUnsafe(parent);
This method returns `EitherAsync` but both `ParseUnsafe` and multiple filesystem operations can throw exceptions which are not caught with e.g. `Try`.

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/GenePoolBase.cs
> +    protected static GenesetTagManifestData ReadGeneSetManifest(string json)
`ReadGeneSetManifest` and `ReadGeneManifest` are unused

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/RepositoryGenePool.cs
> +                var hashAlg = CreateHashAlgorithm(hashAlgName);
Should be `using var` as `HashAlgorithm` is disposable

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/RepositoryGenePool.cs
> +                    throw new VerificationException($"Failed to verify hash of gene part '{messageName}'");
Not sure if we should throw `VerificationException`. According to the docs, it has specific meaning related to type safety.

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/RepositoryGenePool.cs
> +                    var cryptoStream = new CryptoStream(responseStream, hashAlg, CryptoStreamMode.Read);
Should be `await using var`, `CryptoStream` is disposable and actually does something on dispose.

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/RepositoryGenePool.cs
> +                    await CopyToAsync(cryptoStream, tempFileStream, reportProgress,
Inside `CopyToAsync()`, the rented buffer is not returned.

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                    //if (Data.BreedConfig != null)
Is the commented out code still needed?

2024-02-08 15:10 UTC, ChristopherMann commented on src/core/src/Eryph.VmManagement/CatletConfigExtensions.cs
> +                let newConfig = breedConfig.Apply(c =>
Is the `Apply()` a pattern which we should use in general? As the code is written, it modifies `breedConfig` in place which is not obvious. Maybe, we can introduce an extension method like this instead:
```
static T CloneWith<T>(this T cloneable, Action<T> action) where T : ICloneable
{
    var result = cloneable.Clone();
    action(result);
    return result;
}
```

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                            : GeneIdentifier.ParseUnsafe(GeneType.Volume, x)) ?? Array.Empty<GeneIdentifier>());
This is the first place in the code path where we try to parse the user provided identifiers. Maybe, it would be better to use `GeneIdentifier.Parse()` in combination with `Fail()` to avoid retries and provide better feedback to the user.

2024-02-08 15:10 UTC, ChristopherMann commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                        .Where(t => t != null && t.StartsWith("gene:"))
Should we actively reject nonempty sources which are not gene references? Currently, these are just silently ignored.

2024-02-08 15:10 UTC, ChristopherMann commented on src/core/src/Eryph.VmManagement/CatletConfigExtensions.cs
> +                        f => ExpandFodderConfig(genepoolReader, f,
If we want to support transitive fodder references, we need to call `ExpandFodderConfig()` recursively in some way. We might also need to need trigger `PrepareGeneCommand` recursively to make sure that the transitive fooder references are present in the local genepool.

2024-02-08 17:33 UTC, fw2568 commented on src/core/src/Eryph.VmManagement/CatletConfigExtensions.cs
> +                        f => ExpandFodderConfig(genepoolReader, f,
nope, see eryph-org/dotnet-configmodel#52

2024-02-08 17:35 UTC, fw2568 commented on src/core/src/Eryph.VmManagement/CatletConfigExtensions.cs
> +                let newConfig = breedConfig.Apply(c =>
using apply is ok, it is a good workaround in cases when we have a stateful instance that has to be modified within functional code.

2024-02-08 17:43 UTC, fw2568 commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/RepositoryGenePool.cs
> +                    throw new VerificationException($"Failed to verify hash of gene part '{messageName}'");
replaced by HashVerificationException

2024-02-08 17:50 UTC, fw2568 commented on src/core/test/Eryph.VmManagement.Test/Eryph.VmManagement.Test.csproj
> +    <LangVersion>latest</LangVersion>
set to 11

2024-02-08 17:51 UTC, fw2568 commented on src/modules/src/Eryph.Modules.VmHostAgent/Genetics/GenePoolBase.cs
> +    protected static GenesetTagManifestData ReadGeneSetManifest(string json)
true

2024-02-08 17:55 UTC, fw2568 commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                    //if (Data.BreedConfig != null)
nope

2024-02-09 09:22 UTC, fw2568 commented on src/core/src/Eryph.VmManagement/VirtualMachine.cs
> +                var parentIdentifier = GeneSetIdentifier.ParseUnsafe(parent);
replaced with ILocalGenePoolReader

2024-02-09 09:22 UTC, fw2568 commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                            : GeneIdentifier.ParseUnsafe(GeneType.Volume, x)) ?? Array.Empty<GeneIdentifier>());
updated as suggested

2024-02-09 09:23 UTC, fw2568 commented on src/modules/src/Eryph.Modules.Controller/Compute/UpdateCatletSaga.cs
> +                        .Where(t => t != null && t.StartsWith("gene:"))
see new version, will also fail now

2024-02-09 13:06 UTC, ChristopherMann approved these changes

2024-02-09 20:02 UTC, merged