Support of environments config for networks
eryph-org/eryph pull request #147
Opened 2024-02-17 00:38 UTC by fw2568

This PR adds handling of environments for project networks: 

- networks are now unique per name **and** environment name (within a single project)
- network of catlet are selected by environment

The environment concepts allows to specify unique networks within the same project for each environment. Using this feature a user can seperate catlets of different environments but the catlets can still reach each other as they are on same project (same router).

2024-02-27 17:33 UTC, ChristopherMann requested changes

2024-02-27 17:33 UTC, ChristopherMann commented on src/data/src/Eryph.StateDb/Migrations/20240216232245_Network_Environments.cs
> +            migrationBuilder.AddColumn<string>(
The lookup expects that the default networks have the environment name `default` but the existing database entries are not populated. Hence, the `ProjectSeeder` fails during startup with a unique constraint violation on the MAC address as it tries to recreate the default network.

2024-02-27 17:33 UTC, ChristopherMann commented on src/data/src/Eryph.StateDb/Model/VirtualNetwork.cs
> +    public string Environment { get; set; }
`Environment` is not included in the corresponding API response for get requests. Side note: the project name is also not populated in the API response.

2024-02-27 18:07 UTC, fw2568 commented on src/data/src/Eryph.StateDb/Migrations/20240216232245_Network_Environments.cs
> +            migrationBuilder.AddColumn<string>(
Please delete DB before testing

2024-02-27 19:01 UTC, fw2568 commented on src/data/src/Eryph.StateDb/Model/VirtualNetwork.cs
> +    public string Environment { get; set; }
fixed the model. added include for project name to #129, as same call is also touched there.

2024-02-27 19:01 UTC, fw2568 commented on src/data/src/Eryph.StateDb/Migrations/20240216232245_Network_Environments.cs
> +            migrationBuilder.AddColumn<string>(
see also #160

2024-02-27 19:26 UTC, fw2568 commented
Validation has to be updated as well: https://github.com/eryph-org/eryph/blob/ec11ac57126b4cd4a868252998b52d46c55db969/src/modules/src/Eryph.Modules.Controller/Networks/NetworkConfigValidator.cs#L96-L98

Checks on name have to consider that same name is allowed in different environments.

2024-03-13 16:55 UTC, ChristopherMann approved these changes

2024-03-13 17:24 UTC, merged