Improve reliability of service startup
eryph-org/eryph pull request #220
Opened 2024-07-18 10:26 UTC by ChristopherMann

This PR verifies during service startup that Hyper-V (VMMS) and WMI are responsive. We retry the check for some time in case the services are not yet responsive.

Closes #176.

2024-07-20 07:39 UTC, fw2568 requested changes
maybe add a double check here in case Hyper-V is removed? did not tested if service will be started at all - but at some point we should at least check if Hyper-V is actually there.

2024-07-26 07:30 UTC, fw2568 approved these changes

2024-07-26 07:30 UTC, fw2568 commented on src/modules/test/Eryph.Modules.VmHostAgent.Test/SystemRequirementsCheckerTests.cs
> +            ));
Have you checked if this is working on Win Servers?

2024-07-26 08:08 UTC, ChristopherMann commented on src/modules/test/Eryph.Modules.VmHostAgent.Test/SystemRequirementsCheckerTests.cs
> +            ));
Yes, tested on Server 2016 and 2022.

2024-07-26 08:15 UTC, merged